#!/bin/bash

# Eclipse would pass PROJ_PATH to make. Use it to strip out project path 
# to shorten messages. Or at least remove path prefix in wine environment.

if [ -z "$PROJ_PATH" ]; then
    PREFIX=${HOME}/.wine/dosdevices/z:
else
    PREFIX=${HOME}/.wine/dosdevices/z:${PROJ_PATH}/
fi
    

function run_lint
{
    wine "c:/lint/lint-nt.exe" \
	-e1904 +v  -i"c:\\lint\\lnt" \
	-i"c:\\lint" env-si std \
	-"format=\n%t:%n: ##%f##:%l: %m\n------\n" ./script/gcc_inc.lnt ./script/defs.lnt ./script/CAB.lnt $*
}

run_lint $* 
#for eclipse editor
#run_lint $* \
#    | sed -e 's#\\#/#g' \
#    | sed -r 's/(.*):([0-9+]*): ##(.*)##:([0-9+]*):/echo -n `winepath -u \3`:; echo -n "\4: \1:\2:"/ge' \
#    | sed -e "s#${PREFIX}##g"

